### PR TITLE
refactor read_to_string + remove clippy

### PR DESCRIPTION
**Pull request by ashleygwilliams**
this PR dos 3 things:
- refactors to use fs::read_to_string
- removes clippy and clippy configuration
- gitignores the cargo lock file and removes it

### CODE REVIEW

**Review by yoshuawuyts — APPROVED** [review]
\o/

**Comment by ashleygwilliams** [comment]
yay travis FINALLY PASSED 😅

**Review by yoshuawuyts — APPROVED** [review]
ahaha, looks great!

**Comment by yoshuawuyts** [comment]
`v0.2.0` :tada:

**Pull request merged**
